application:
  version: 1.0.0
  servers:
  - ip: '127.0.0.1'
    path: '/path1'
  - ip: '127.0.0.2'
    path: '/path2'
   
spring:
  profiles:
    active: local   
  level:
    root: debug
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp   
#handlebars:
#  suffix: .jsp
#  expose-session-attributes: true
    
  import:
    optional:configserver: http://localhost:7070
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cfpy0mnyxcis.us-east-2.rds.amazonaws.com/sys
    username: admin
    password: test12345
    
  
      
#  handlebars:
#  expose-session-attributes: true

env:
  servers: helloworld
  obj:
    number: 10
    sec: 10s

jwt:
  token:
    secret-key: "hello"
    expTime: 1800000
    issuer: "gunkim"    

    
mybatis:
    #type-aliases-package: model 사용 시 매핑할 패키지 경로를 작성합니다.
    mapper-locations: mappers/**/*.xml
    
spring:
  kafka:
   consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id-oing
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer



   
